/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Mesa.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Mesa.glb')
  return (
    <group {...props} dispose={null}>
      
      
      
     
     
      

     
    </group>
  )
}

useGLTF.preload('/Mesa.glb')
