/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Pomo.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pomo(props) {
    const { nodes, materials } = useGLTF('./models/Pomo.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.polySurface1.geometry} material={materials.standardSurface1} position={[0, 0, 0.07]} />
        </group>
    )
}

useGLTF.preload('./models/Pomo.glb')
